name: Daily Update

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours (at 00:00 and 12:00 UTC)
  workflow_dispatch: # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the full history so rebase works properly

      - name: Pull and rebase to sync with remote
        run: |
          git pull --rebase

      - name: Update README and commit
        run: |
          echo " " >> README.md
          git config user.name "seb7wake"
          git config user.email "seb7wake@gmail.com"
          git add README.md
          git commit -m "Shipping changes"

      - name: Push changes
        run: |
          git push
