name: Daily Update

on:
  schedule:
    # - cron: "0 0 * * *" # Runs at 00:00 UTC every day
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the full history so rebase works properly

      - name: Pull and rebase to sync with remote
        run: |
          git pull --rebase

      - name: Update README and commit
        run: |
          echo "Updated on $(date)" >> README.md
          git config user.name "seb7wake"
          git config user.email "seb7wake@gmail.com"
          git add README.md
          git commit -m "Daily README update"

      - name: Push changes
        run: |
          git push
